words = [
    "isort",
    "jax",
    "langserver",
    "marimo",
    "nixfmt",
    "numtide",
    "optax",
    "polars",
    "pyarrow",
    "pyright",
    "seaborn",
    "stdenv",
    "taplo",
    "treefmt",
    "venv",
]
