words = [
  "cuda",
  "direnv",
  "iex",
  "irm",
  "isort",
  "jax",
  "langserver",
  "lstm",
  "marimo",
  "nixfmt",
  "numtide",
  "optax",
  "polars",
  "pyarrow",
  "pyright",
  "seaborn",
  "stdenv",
  "taplo",
  "treefmt",
  "venv",
]
